# Generated by Django 2.2 on 2021-08-18 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('worker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='worker.Worker')),
                ('grade', models.IntegerField(default=1, verbose_name='Оценка')),
            ],
            options={
                'verbose_name': 'Директор',
                'db_table': 'directors',
            },
            bases=('worker.worker',),
        ),
        migrations.CreateModel(
            name='EducationOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('mail', models.CharField(max_length=30, verbose_name='Адрес почты')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'education_office',
            },
        ),
        migrations.CreateModel(
            name='GeneralOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('mail', models.CharField(max_length=30, verbose_name='Адрес почты')),
                ('name', models.TextField(verbose_name='Название головного офиса ')),
            ],
            options={
                'db_table': 'office',
            },
        ),
        migrations.CreateModel(
            name='OrderedWorker',
            fields=[
                ('worker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='worker.Worker')),
            ],
            options={
                'abstract': False,
            },
            bases=('worker.worker',),
        ),
        migrations.AddField(
            model_name='department',
            name='education_office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.EducationOffice'),
        ),
        migrations.AddField(
            model_name='department',
            name='office',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='worker.GeneralOffice'),
        ),
    ]
