# Generated by Django 2.2 on 2021-08-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_auto_20210818_0941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedWorker',
        ),
        migrations.CreateModel(
            name='OrderedWorker',
            fields=[
            ],
            options={
                'ordering': ['first_name', 'startwork_date'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('worker.worker',),
        ),
    ]
